### ISSUE TITLE
[Bug] Links given as markdown in Readme appear as strings & the writing shifts sideways because it overflows

### ISSUE THREAD

**Issue by ramazansancar** [code-a-man/calisma-mekanlari-app#1]
There should be a maximum character limit for texts or it should expand the box it is in by sliding to the bottom line to prevent overflow.

Or, as another suggestion, if the content of the space is long, the modal can be opened with "read more" and converted to a structure that will see the whole.

Screenshots:

![image](https://github.com/code-a-man/calisma-mekanlari-app/assets/8878055/b08fc950-092c-4857-8a10-29d689ebe019)

**Comment by code-a-man** [comment]
I actually looked into markdown link problem the other day. I think it needs some parser thing markdown to html.

Actually just links causes overflow otherwise normal text doesnt overflow.

When markdown link problem solved there will be no overflow but read more feature would also be nice in terms of maintaining cards alignment.

**Comment by code-a-man** [comment]
Hey @ramazansancar I fixed markdown link problem and added minimal read more button thanks for your feedback
